version: "3"

services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: bbuster_flix
    ports:
      - 3306:3306
    network_mode: host

  cache:
    image: redis:alpine
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    network_mode: host

  app:
    image: node:14-alpine
    container_name: app
    restart: on-failure
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: develop
      PORT: 3000
      TOKEN_SECRET: s5nh4mu1mu1f0rt3
      JTI: N3wJwTt0K3n
      DB_DIALECT: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: bbuster_flix
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    depends_on:
      - db
      - cache
    ports:
      - 3000:3000
    network_mode: host
    command: sh -c "npm install && npm run migration && npm run seed && npm start"
