version: '3.1'
services: 
  db:
    container_name: mysql
    image: mysql
    networks: 
      - minharede
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bbuster_flix
      - TZ=America/Sao_Paulo    
    volumes: 
    - ./app/:/usr/src/app
    - type: volume
      source: db-volume
      target: /data/db
    ports: 
      - 3308:3306

  redis:
    container_name: redis
    image: redis
    networks: 
      - minharede
    ports:
      - 6379:6379

  apps:
    container_name: apps
    build: .
    networks: 
      - minharede
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    depends_on: 
     - db
     - redis
    environment:
      - HOST=mysql
      - USER=root
      - DATABASE=bbuster_flix
      - PASSWORD=root
      - DIALECT=mysql
      - DB_PORT=3308
      - WAIT_HOSTS=db:3308
      - WAIT_HOSTS=redis:6379    
    ports: 
     - 3000:3000

volumes:
  db-volume:

networks: 
  minharede:
